### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by dgsierra** [rebel216/LeaderBoard#6]
@rebel216 You have fulfilled  the requirements of the activity!

![completed](https://user-images.githubusercontent.com/62531899/186182078-80f2dd43-3e77-4430-8842-ce7e156ff614.gif)

[Optional]
-It would be nice to work a little bit in the responsiveness of the project in case somebody try it from a mobil device or a small screen.

**Comment by rebel216** [comment]
Yes I will do that . Thanks You 👍
